CNAME_FINGERPRINTS = {
    # Nomes padronizados para corresponder aos templates e CNAMEs
    "Aftership": ["aftership"], 
    "AgileCRM": ["agilecrm\\.com"],
    "Aha": ["aha\\.io"],
    "Airee": ["airee\\.ru"],
    "Anima": ["animaapp\\.io"],
    "Announcekit": ["announcekit\\.app"],
    
    # Cloud Providers
    "AWS_S3": ["s3\\.amazonaws\\.com", "s3-website-"],
    "AWS_Beastalk": ["elasticbeanstalk\\.com"],
    "AWS_ELB": ["elb\\.amazonaws\\.com"],
    "Wasabi_S3": ["wasabisys\\.com"],
    "AWS_Global_Accelerator": ["awsglobalaccelerator\\.com"],
    "Azure": [
        "cloudapps\\.net", "azurewebsites\\.net", "cloudapp\\.net", "cloudapp\\.com", 
        "azureedge\\.net", "azurefd\\.net", "azurestaticapps\\.net", "cloudapp\\.azure\\.com", 
        "storage\\.azure\\.net", "trafficmanager\\.net", 
        "blob\\.core\\.windows\\.net", "azure-api\\.net", "azurehdinsight\\.net", 
        "azurecontainer\\.io", "database\\.windows\\.net", "azuredatalakestore\\.net", 
        "search\\.windows\\.net", "azurecr\\.io", "redis\\.cache\\.windows\\.net", 
        "servicebus\\.windows\\.net", "visualstudio\\.com"
    ],
    "Google_Apps": ["ghs\\.googlehosted\\.com"],
    "Google_Cloud_Storage": ["storage\\.googleapis\\.com"], 
    "Cloudflare_Pages": ["pages\\.dev"], 
    
    # PaaS/Hosting
    "Heroku": ["herokudns\\.com", "herokuapp\\.com"],
    "Netlify": ["netlify\\.com", "netlify\\.app"],
    "Vercel": ["cname\\.vercel-dns\\.com"],
    "Github": ["github\\.io", "github\\.com"],
    "Surge": ["surge\\.sh", "na-west1\\.surge\\.sh"],
    "Pantheon": ["pantheonsite\\.io"],
    "Kinsta": ["kinsta\\.cloud"],
    "Clever": ["clever-cloud\\.com"], 
    "Meteor": ["meteor\\.com"], 
    "Platform_SH": ["platformsh\\.site", "platform\\.sh"],
    "Ngrok": ["ngrok\\.io"], # Adicionado Ngrok

    # E-commerce, Marketing, CMS
    "Shopify": ["myshopify\\.com"],
    "BigCartel": ["bigcartel\\.com"],
    "Launchrock": ["launchrock\\.com"],
    "Leadpages": ["leadpages\\.net", "leadpages\\.co"],
    "GetResponse": ["getresponsepages\\.com", "getresponse\\.com"],
    "Wishpond": ["wishpond\\.com"],
    "HubSpot": ["hubspot\\.net", "hubspot"],
    "Unbounce": ["unbouncepages\\.com", "instapage\\.com"],
    "Simplebooklet": ["simplebooklet\\.com"],
    "SmugMug": ["smugmug\\.com"],
    "Tilda": ["tilda\\.ws", "tilda\\.cc"],
    "Strikingly": ["strikinglydn\\.com", "s\\.strikinglydns\\.com"],
    "WordPress": ["wordpress\\.com", "wpengine\\.com"],
    "Wix": ["wixsite\\.com"],
    "CargoCollective": ["cargo\\.site", "cargocollective\\.com"],

    # Docs, Suporte, CRM
    "Zendesk": ["zendesk\\.com", "desk\\.com"], 
    "HelpScout": ["helpscoutdocs\\.com", "helpscoutsites\\.com"],
    "HelpDocs": ["helpdocs\\.io", "dot-docs\\.com"],
    "Helprace": ["helprace\\.com"],
    "Freshdesk": ["freshdesk\\.com", "freshservice\\.com"],
    "Ghost": ["ghost\\.io"],
    "Readthedocs": ["readthedocs\\.io", "readthedocs\\.org", "readthedocsonline\\.com"],
    "GitBook": ["gitbook\\.io"],
    "Readme": ["readme\\.io"], 
    "Intercom": ["intercom\\.website"],
    "Uservoice": ["uservoice\\.com"],
    
    # Outros Serviços
    "CampaignMonitor": ["campaignmonitor\\.com"],
    "Bitbucket": ["bitbucket\\.io"],
    "JazzHR": ["jazzhr\\.com"],
    "Mailgun": ["mailgun\\.org"],
    "Mashery": ["mashery\\.com"],
    "Pingdom": ["pingdom\\.com"],
    "UptimeRobot": ["uptimerobot\\.com", "stats\\.uptimerobot\\.com"],
    "GoHire": ["gohire\\.io"],
    "Spreed": ["sprintful\\.com"], 
    "Proposify": ["proposify\\.biz"],
    "Wufoo": ["wufoo\\.com"],
    "JetBrains": ["jetbrains\\.com", "youtrack\\.cloud"],
    "Flexbe": ["flexbe\\.net"],
    "Frontify": ["frontify\\.com"],
    "Gemfury": ["gemfury\\.com", "furyns\\.com"],
    "SurveyGizmo": ["surveygizmo\\.com"],
    "SurveySparrow": ["surveysparrow\\.com"],
    "Tave": ["tave\\.com"],
    "Teamwork": ["teamwork\\.com"],
    "Uberflip": ["uberflip\\.com", "read\\.uberflip\\.com"],
    "Vend": ["vendcommerce\\.com"],
    "Branch": ["custom\\.bnc\\.lt"], 
    "Acquia": ["acquia-sites\\.com"],
    "SmartJobBoard": ["smartjob\\.com"],
    "Squadcast": ["squadcast\\.io"], 
}


TAKEOVER_MAP = {
    "Aftership": "takeovers/aftership-takeover.yaml",
    "AgileCRM": "takeovers/agilecrm-takeover.yaml",
    "Aha": "takeovers/aha-takeover.yaml",
    "Airee": "takeovers/airee-takeover.yaml",
    "Anima": "takeovers/anima-takeover.yaml",
    "Announcekit": "takeovers/announcekit-takeover.yaml",
    "AWS_S3": "takeovers/aws-bucket-takeover.yaml",
    "BigCartel": "takeovers/bigcartel-takeover.yaml",
    "Bitbucket": "takeovers/bitbucket-takeover.yaml",
    "CampaignMonitor": "takeovers/campaignmonitor-takeover.yaml",
    "Canny": "takeovers/canny-takeover.yaml",
    "Cargo": "takeovers/cargo-takeover.yaml",
    "CargoCollective": "takeovers/cargocollective-takeover.yaml",
    "Clever": "takeovers/clever-takeover.yaml",
    "Flexbe": "takeovers/flexbe-takeover.yaml",
    "Framer": "takeovers/framer-takeover.yaml",
    "Frontify": "takeovers/frontify-takeover.yaml",
    "Gemfury": "takeovers/gemfury-takeover.yaml",
    "GetResponse": "takeovers/getresponse-takeover.yaml",
    "Ghost": "takeovers/ghost-takeover.yaml",
    "GitBook": "takeovers/gitbook-takeover.yaml",
    "Github": "takeovers/github-takeover.yaml",
    "GoHire": "takeovers/gohire-takeover.yaml",
    "Greatpages": "takeovers/greatpages-takeover.yaml",
    "Hatenablog": "takeovers/hatenablog-takeover.yaml",
    "HelpDocs": "takeovers/helpdocs-takeover.yaml",
    "HelpJuice": "takeovers/helpjuice-takeover.yaml",
    "Helprace": "takeovers/helprace-takeover.yaml",
    "HelpScout": "takeovers/helpscout-takeover.yaml",
    "HubSpot": "takeovers/hubspot-takeover.yaml",
    "Intercom": "takeovers/intercom-takeover.yaml",
    "JazzHR": "takeovers/jazzhr-takeover.yaml",
    "JetBrains": "takeovers/jetbrains-takeover.yaml",
    "Kinsta": "takeovers/kinsta-takeover.yaml",
    "Launchrock": "takeovers/launchrock-takeover.yaml",
    "Leadpages": "takeovers/leadpages-takeover.yaml",
    "Mailgun": "takeovers/mailgun-takeover.yaml",
    "Mashery": "takeovers/mashery-takeover.yaml",
    "Meteor": "takeovers/meteor-takeover.yaml",
    "Netlify": "takeovers/netlify-takeover.yaml",
    "Ngrok": "takeovers/ngrok-takeover.yaml",
    "Pagewiz": "takeovers/pagewiz-takeover.yaml",
    "Pantheon": "takeovers/pantheon-takeover.yaml",
    "Pingdom": "takeovers/pingdom-takeover.yaml",
    "Proposify": "takeovers/proposify-takeover.yaml",
    "Readme": "takeovers/readme-takeover.yaml",
    "ReadTheDocs": "takeovers/readthedocs-takeover.yaml",
    "RedirectPizza": "takeovers/redirect-pizza-takeover.yaml",
    "Shopify": "takeovers/shopify-takeover.yaml",
    "ShortIO": "takeovers/short-io.yaml",
    "Simplebooklet": "takeovers/simplebooklet-takeover.yaml",
    "SmartJobBoard": "takeovers/smartjob-takeover.yaml",
    "SmugMug": "takeovers/smugmug-takeover.yaml",
    "Softr": "takeovers/softr-takeover.yaml",
    "Spreed": "takeovers/sprintful-takeover.yaml",
    "Squadcast": "takeovers/squadcast-takeover.yaml",
    "Strikingly": "takeovers/strikingly-takeover.yaml",
    "Surge": "takeovers/surge-takeover.yaml",
    "SurveyGizmo": "takeovers/surveygizmo-takeover.yaml",
    "SurveySparrow": "takeovers/surveysparrow-takeover.yaml",
    "Tave": "takeovers/tave-takeover.yaml",
    "Teamwork": "takeovers/teamwork-takeover.yaml",
    "Tilda": "takeovers/tilda-takeover.yaml",
    "Uberflip": "takeovers/uberflip-takeover.yaml",
    "Uptime": "takeovers/uptime-takeover.yaml",
    "UptimeRobot": "takeovers/uptimerobot-takeover.yaml",
    "Uservoice": "takeovers/uservoice-takeover.yaml",
    "Vend": "takeovers/vend-takeover.yaml",
    "Wasabi_S3": "takeovers/wasabi-bucket-takeover.yaml",
    "Wishpond": "takeovers/wishpond-takeover.yaml",
    "Wix": "takeovers/wix-takeover.yaml",
    "WordPress": "takeovers/wordpress-takeover.yaml",
    "WorkSites": "takeovers/worksites-takeover.yaml", 
    "Wufoo": "takeovers/wufoo-takeover.yaml",
    "Zendesk": "takeovers/zendesk-takeover.yaml"
}